# Generated by Django 5.2.6 on 2025-09-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=20, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_articulo', to='myapp.grupoarticulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='linea_articulo', to='myapp.lineaarticulo')),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['codigo_articulo'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('lista_precio_id', models.UUIDField(primary_key=True, serialize=False)),
                ('precio_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_precio', to='myapp.articulo')),
            ],
            options={
                'db_table': 'listas_precios',
                'ordering': ['articulo__codigo_articulo'],
            },
        ),
    ]
